# list of all recipes
help:
    @just -f {{ justfile() }} --list --unsorted

# install rama cli
rama-setup:
    echo TBD

start-duckdb:
    direnv exec . duckdb -init bin/init.sql

sql-migrate-dev:
    direnv exec . sql-migrate up -env=dev -config=migrations/dbconfig.yml

sql-migrate-test:
    direnv exec . sql-migrate up -env=test -config=migrations/dbconfig.yml

psql-dev:
    direnv exec . psql -h localhost -p <{ postgres-port }> -U <{ postgres-user }> <{ postgres-dbname }>

psql-test:
    direnv exec . psql -h localhost -p <{ postgres-port-test }> -U <{ postgres-user }> <{ postgres-dbname }>

psql-staging:
    direnv exec . env PGPASSWORD=<{ postgres-password-staging }> psql -h <{ postgres-host-staging }> -p <{ postgres-port-staging }> -U <{ postgres-user-staging }> <{ postgres-dbname-staging }>

kill-dev:
    lsof -t -i :<{ postgres-port }> | xargs -r kill
    rm -f /tmp/port-<{ postgres-port }>

kill-test:
    lsof -t -i :<{ postgres-port-test }> | xargs -r kill
    rm -f /tmp/port-<{ postgres-port-test }>

kill-all: kill-dev kill-test
