name: rama-jdbc CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      - name: download big-container
        run: docker pull ghcr.io/amiorin/big-container:latest
      - name: runs rama-jdbc tests
        id: run_tests
        run: >-
          docker run
          --rm
          -u vscode
          ghcr.io/amiorin/big-container:latest
          fish -c 'git clone https://github.com/amiorin/rama-jdbc.git --branch main --single-branch --depth=1
          && cd rama-jdbc
          && bb build
          && direnv allow
          && direnv exec . clojure -M:shared:test'
